FROM node:latest
WORKDIR '/src/app'

# # add `/usr/src/app/node_modules/.bin` to $PATH
# ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json ./
RUN npm install
RUN npm install react-scripts -g
COPY . .

# start app
CMD ["npm", "start"]